### ISSUE TITLE
Great Project!

### ISSUE THREAD

**Issue by argosopentech** [dothq/translate#7]
Hi!

This looks like an awesome project! [LibreTranslate](https://libretranslate.com) is great but I'm partial towards the minimalist style.

Feel free to pass relevant support requests my way, I'm normally pretty responsive on GitHub and the [LibreTranslate Forum](https://community.libretranslate.com).

Best,

[P.J.](https://github.com/PJ-Finlay)

**Comment by johnpaulbin** [comment]
Thank you for checking out this project!

We are aiming towards more minimal / lightweight infrastructure for our service to fit on very light machines.
As an example, we have a small demonstration API running entirely in Flask (using selected models)

We are soon going to experiment with temperature, top p, etc. to see how well we can use it in specific applications, like https://github.com/dothq/dialect

Awesome work on ArgosTranslate!!! See you around hopefully.
